### ISSUE TITLE
Local Notification Doesn't Show in iOS 11

### ISSUE THREAD

**Issue by deanilvincent** [edsnider/LocalNotificationsPlugin#26]
If this issue is for a new feature, please skip the "Bug" section and fill out the "Feature Request" section at the bottom.

## Bug

Plugin Version:  2.1.0
Platform: xcode 9 for iOS 11 and VS 15.3.5
Device/Hardware:  Mac and Windows

### Expected behavior
Should show simple notification on iOS 11 emulator

### Actual behavior
Doesn't show any local notification in all iOS 11 emulator that I've tried. This includes: IPhone X iOS11, iPhone SE iOS11, iPhone 8 Plus iOS11, iPhone 7 iOS11
### Steps to reproduce the behavior
- 
- 

## Feature Request

Feature description:

**Comment by higher-faster-better** [comment]
Any solution? I have same issue in iOS 11

**Comment by higher-faster-better** [comment]
@deanilvincent I've tested it on real device iPhone 6 but not showing notification. Does it work on your device?

**Comment by deanilvincent** [comment]
Same problem with the emulator @higher-faster-better

**Comment by deanilvincent** [comment]
I guess it's not yet supported in iOS 11. In previous iOS I've tested before and it's working properly.

**Comment by higher-faster-better** [comment]
@deanilvincent Finally I've fixed it.
Create new class named UserNotificationCenterDelegate in IOS project.
Then add this code.
```
public class UserNotificationCenterDelegate : UNUserNotificationCenterDelegate
    {
        public override void WillPresentNotification(UNUserNotificationCenter center, UNNotification notification, Action<UNNotificationPresentationOptions> completionHandler)
        {
            // Tell system to display the notification anyway or use
            // `None` to say we have handled the display locally.
            completionHandler(UNNotificationPresentationOptions.Alert);
        }
    }
```

Finally add this code to your FinishedLaunching in app delegate.
```
// request local notification permission
            if (UIDevice.CurrentDevice.CheckSystemVersion(10, 0))
            {
                // Ask the user for permission to get notifications on iOS 10.0+
                UNUserNotificationCenter.Current.RequestAuthorization(
                    UNAuthorizationOptions.Alert | UNAuthorizationOptions.Badge | UNAuthorizationOptions.Sound,
                    (approved, error) => { });

                // Watch for notifications while app is active
                UNUserNotificationCenter.Current.Delegate = new UserNotificationCenterDelegate();
            }
            else if (UIDevice.CurrentDevice.CheckSystemVersion(8, 0))
            {
                // Ask the user for permission to get notifications on iOS 8.0+
                var settings = UIUserNotificationSettings.GetSettingsForTypes(
                    UIUserNotificationType.Alert | UIUserNotificationType.Badge | UIUserNotificationType.Sound,
                    new NSSet());

                UIApplication.SharedApplication.RegisterUserNotificationSettings(settings);
            }
```

I think you already added similar code to your app delegate.
But do not miss this line.
```
// Watch for notifications while app is active
                UNUserNotificationCenter.Current.Delegate = new UserNotificationCenterDelegate();
```

**Comment by pooran** [comment]
Still with above changes, it is not working.

**Comment by Rousseau38** [comment]
@higher-faster-better  were you able to get this to work while the app was in the background?

Thanks

**Comment by Pirate911** [comment]
I have the same issue even after trying the suggested code by @higher-faster-better . I think it has issue with IOS 11

**Comment by Pirate911** [comment]
Sorry , it works fine after I added the latest pre version 3.0.0

**Comment by robintschroeder** [comment]
In order to make it work for iOS 11.x, you need to add:

  // Watch for notifications while app is active
                UNUserNotificationCenter.Current.Delegate = new UserNotificationCenterDelegate();

see @higher-faster-better 's post above to see exactly where that goes.

**Comment by edsnider** [comment]
As mentioned above, a `UNUserNotificationCenterDelegate` class is required if you want to display alerts while the app is in the foreground. See the README and the sample in the repo for implementation details: https://github.com/edsnider/LocalNotificationsPlugin/blob/master/samples/LocalNotificationsSample/LocalNotificationsSample.iOS/AppDelegate.cs#L20  
https://github.com/edsnider/LocalNotificationsPlugin/blob/master/samples/LocalNotificationsSample/LocalNotificationsSample.iOS/UserNotificationCenterDelegate.cs
