### ISSUE TITLE
.Net Standard 2.0

### ISSUE THREAD

**Issue by jerryg78258** [edsnider/LocalNotificationsPlugin#36]
If possible please provide a netstandard 2.0 NuGetPackage.

## Bug

Plugin Version:  
Platform (e.g., Android v21):  
Device/Hardware:  

### Steps to reproduce the behavior
- 
- 

## Feature Request

Feature description:

**Comment by edsnider** [comment]
It's available in a pre-release NuGet: https://www.nuget.org/packages/Xam.Plugins.Notifier/3.0.0-beta14

**Comment by edsnider** [comment]
There is now a stable release of 3.0.0 available on NuGet.
