### ISSUE TITLE
Support for Android apps targeting Android 8.0+ 

### ISSUE THREAD

**Issue by darkice-matt-crombie** [edsnider/LocalNotificationsPlugin#38]
## Feature Request

Feature description:  

Support for Android apps targeting Android 8.0+ would be great. Notifications for apps built against API 26+ don't currently work it seems. Looking through the source it looks like they need to be configured to use notification channels for this, as per this blog post: 

https://blog.xamarin.com/android-oreo-notification-channels/

**Comment by sunnysonic** [comment]
Have you tried on a real device? Working here, but not in the emulator.

**Comment by karlingen** [comment]
Same here. Doesn't work in simulator. I haven't tried on device since I don't own one currently. I hope someone else can confirm this?

**Comment by vasiliy-s** [comment]
Does not work on Note 8

**Comment by mathewgrabau** [comment]
Not working on Samsung Galaxy S8

**Comment by finnsea** [comment]
Am also interested in this. Currently just targeting an Android 7.1, but would love to be able to update.

**Comment by kylewhittington** [comment]
I ended up just building my own implementation of this. The key thing is that Android 8.0+ needs the ChannelId to be set. This means you need to create a channel first and then add the notification to the channel. The catch is that if you use the Mono.Android 8.0+ you have access to these methods for adding channel... but if you then run on Android <8.0, you get a "not implemented" exception for the Java method it's trying to call. So.... you need to differentiate between them in your code to use different implementations of the Notification Builder depending on version that it's running on.

I quickly pulled this Notifications interface together and then just consume it through the dependency service... It's not refined or polished by any stretch of the imagination, but I got it working this afternoon and thought it may help some others in a similar predicament...

`public class Notifications : INotifications
    {
        private NotificationManager _notificationMananger;
        private const string GeneralChannelId = "com.yourapp.general";
        private const string GeneralChannelName = "General";
        private const NotificationImportance GeneralChannelImportance = NotificationImportance.Default;

        public Notifications()
        {
            _notificationMananger = Forms.Context.GetSystemService(Context.NotificationService) as NotificationManager;
            // Set up channels
            if (Build.VERSION.SdkInt >= Build.VERSION_CODES.O)
            {
                if (!_notificationMananger.NotificationChannels.Any(x => x.Id == GeneralChannelId))
                {
                    NotificationChannel generalChannel = new NotificationChannel(GeneralChannelId, GeneralChannelName, GeneralChannelImportance);
                    generalChannel.EnableVibration(false);
                    generalChannel.LockscreenVisibility = NotificationVisibility.Public;
                    _notificationMananger.CreateNotificationChannel(generalChannel);
                }
            }
        }

        public void Send(string title, string text, int id, bool isOngoing)
        {
            try
            {
                if (Build.VERSION.SdkInt >= Build.VERSION_CODES.O)
                {
                    Notification.Builder builder = new Notification.Builder(Forms.Context, GeneralChannelId)
                        .SetContentTitle(title)
                        .SetContentText(text)
                        .SetSmallIcon(Resource.Drawable.X1)
                        .SetOngoing(isOngoing);

                    Notification notification = builder.Build();
                    _notificationMananger.Notify(id, notification);
                }
                else
                {
                    NotificationCompat.Builder builder = new NotificationCompat.Builder(Forms.Context)
                    .SetContentTitle(title)
                    .SetContentText(text)
                    .SetSmallIcon(Resource.Drawable.X1)
                    .SetOngoing(isOngoing);

                    Notification notification = builder.Build();
                    _notificationMananger.Notify(id, notification);
                }
                
            }
            catch (Exception ex)
            {
                
            }
        }

        public void Remove(int id)
        {
            _notificationMananger.Cancel(id);
        }
  }`

**Comment by santiagobiart** [comment]
Hi @kylewhittington where should I put this code? in Mainactivity.cs?  
Thanks in advance!

**Comment by santiagobiart** [comment]
Thanks @kylewhittington! I'll try it

**Comment by maculit** [comment]
Thanks @kylewhittington! I added your code into the plugin code. So far it's working for me. 
`
      
        /// <summary>
        /// Get or Set Resource Icon to display
        /// </summary>
        public static int NotificationIconId { get; set; }

        /// <summary>
        /// Get or Set id of the default channel for the app
        /// </summary>
        public static string GeneralChannelId { get; set; }

        /// <summary>
        /// Get or Set the user visible name of this channel.
        /// </summary>
        public static string GeneralChannelName { get; set; } = "General";

        /// <summary>
        /// Get or Set this channel's notification importance
        /// </summary>
        public static NotificationImportance GeneralChannelImportance { get; set; } = NotificationImportance.Default;

        /// <summary>
        /// Show a local notification
        /// </summary>
        /// <param name="title">Title of the notification</param>
        /// <param name="body">Body or description of the notification</param>
        /// <param name="id">Id of the notification</param>
        public void Show(string title, string body, int id = 0)
        {            
            NotificationManager notificationManager = Android.App.Application.Context.GetSystemService(Context.NotificationService) as NotificationManager;

            if (Build.VERSION.SdkInt >= BuildVersionCodes.O)
            {
                if (GeneralChannelId == null)
                {                    
                    throw new NullReferenceException("[LocalNotificationsImplementation] You need to defined GeneralChannelId for Android (Build.VERSION.SdkInt >= BuildVersionCodes.O). " +
                        "Example: LocalNotificationImplementation.GeneralChannelId = \"com.yourapp.general\"");
                }
                else
                {
                    if (!notificationManager.NotificationChannels.Any(x => x.Id == GeneralChannelId))
                    {

                        NotificationChannel generalChannel = new NotificationChannel(GeneralChannelId, GeneralChannelName, GeneralChannelImportance);
                        generalChannel.EnableVibration(false);
                        generalChannel.LockscreenVisibility = NotificationVisibility.Public;
                        notificationManager.CreateNotificationChannel(generalChannel);
                    }
                    Notification.Builder builder = new Notification.Builder(Application.Context, GeneralChannelId)
                        .SetContentTitle(title)
                        .SetContentText(body)
                        .SetAutoCancel(true)
                        .SetOngoing(false);

                    if (NotificationIconId != 0)
                    {
                        builder.SetSmallIcon(NotificationIconId);
                    }
                    else
                    {
                        builder.SetSmallIcon(Resource.Drawable.plugin_lc_smallicon);
                    }
                    var resultIntent = GetLauncherActivity();
                    resultIntent.SetFlags(ActivityFlags.NewTask | ActivityFlags.ClearTask);
                    var stackBuilder = Android.Support.V4.App.TaskStackBuilder.Create(Application.Context);
                    stackBuilder.AddNextIntent(resultIntent);
                    var resultPendingIntent =
                        stackBuilder.GetPendingIntent(0, (int)PendingIntentFlags.UpdateCurrent);
                    builder.SetContentIntent(resultPendingIntent);
                    notificationManager.Notify(id, builder.Build());
                }
            }
            else 
            {
                NotificationCompat.Builder builder = new NotificationCompat.Builder(Application.Context);
                builder.SetContentTitle(title);
                builder.SetContentText(body);
                builder.SetAutoCancel(true);

                if (NotificationIconId != 0)
                {
                    builder.SetSmallIcon(NotificationIconId);
                }
                else
                {
                    builder.SetSmallIcon(Resource.Drawable.plugin_lc_smallicon);
                }

                var resultIntent = GetLauncherActivity();
                resultIntent.SetFlags(ActivityFlags.NewTask | ActivityFlags.ClearTask);
                var stackBuilder = Android.Support.V4.App.TaskStackBuilder.Create(Application.Context);
                stackBuilder.AddNextIntent(resultIntent);
                var resultPendingIntent =
                    stackBuilder.GetPendingIntent(0, (int)PendingIntentFlags.UpdateCurrent);
                builder.SetContentIntent(resultPendingIntent);

                notificationManager.Notify(id, builder.Build());
            }

            
        }
`

**Comment by joncortez** [comment]
Is the code here going to be fixed to support apps targeting Android 8.0+? @maculit Wanna submit a PR for that?

**Comment by santiagobiart** [comment]
Hi  @maculit in which file did you add the code?

**Comment by maculit** [comment]
@joncortez will submit PR soon. @santiagobiart I edited LocalNotificationsImplementation.cs in Android project of the plugin.

**Comment by edsnider** [comment]
Support for Android Oreo+ is available in the latest pre-release NuGet for testing: https://www.nuget.org/packages/Xam.Plugins.Notifier/3.0.1-beta20
