### ISSUE TITLE
Buttons and visibility on the locksceen

### ISSUE THREAD

**Issue by nabrezzelt** [edsnider/LocalNotificationsPlugin#39]
## Feature Request
Is it possible to add buttons in the Notfication (for music-player controlling) and show them on the lockscreen? 

If it is already possible - how?

Thanks :smile: 

[Example](https://codelabs.developers.google.com/codelabs/android-music-player/img/1b573ca18bd007e4.png)

**Comment by edsnider** [comment]
@nabrezzelt this library currently doesn't support buttons/actions on notifications (although I do have plans to add that).  However, if you're specifically trying to do a media player take a look at this plugin: https://github.com/martijn00/XamarinMediaManager - it sets up the Android notifications specifically for media.
