### ISSUE TITLE
Breaking change in 2.1.0 regarding key in UserInfo

### ISSUE THREAD

**Issue by bokmadsen** [edsnider/LocalNotificationsPlugin#6]
## Bug

Plugin Version:  2.1.0
Platform (e.g., Android v21):  iOS 10.x
Device/Hardware:  Simulator and devices

### Expected behavior
In AppDelegate.ReceivedLocalNotification() the key "LocalNotificationKey" is expected in UserInfo

### Actual behavior
The "LocalNotificationKey" key is not present. This is because in iOS 10 the new notification framework is used, and it doesn't use "LocalNotificationKey"

### Steps to reproduce the behavior
- Create local notification using Plugin.LocalNotifications.CrossLocalNotifications.Current.Show("Test","Test",-1) 
- Inspect UserInfo in AppDelegate.ReceivedLocalNotification() and see the key is missing

**Comment by edsnider** [comment]
`ReceivedLocalNotification` is deprecated in iOS 10+.  You instead should implement a `UNUserNotificationCenterDelegate` class and override `WillPresentNotification` (see the README and sample).  

This plugin uses `UserInfo` for iOS 9.x and older to provide the notification's identifier.  However, on iOS 10+ the identifier can be accessed in the `UNNotification`'s `Request` property.  For example, in `WillPresentNotification` you can access it via `notification.Request.Identifier`.
