### ISSUE TITLE
remove notification

### ISSUE THREAD

**Issue by DevAdcoop** [edsnider/LocalNotificationsPlugin#65]
## Feature Request

Hi, it is possible to remove an old notification,
if i set a notification alert nextmonth and i need to change the alert period , how can we do this???
Thanks

**Comment by edsnider** [comment]
You can cancel the notification using the [`Cancel()`](https://github.com/edsnider/localnotificationsplugin/blob/master/src/Plugin.LocalNotifications.Abstractions/INotifierService.cs#L31) method and then reschedule it.
