### ISSUE TITLE
Assembly 'Xamarin.Android.Support.v4' is using '[assembly: Java.Interop.JavaLibraryReferenceAttribute]', which is no longer supported.

### ISSUE THREAD

**Issue by jimiatnymbl** [edsnider/LocalNotificationsPlugin#69]
## Bug
Updating to the latest Xamarin.Forms (v4.7.0.1239), I am now receiving the following error:

"error XA0121: Assembly 'Xamarin.Android.Support.v4' is using '[assembly: Java.Interop.JavaLibraryReferenceAttribute]', which is no longer supported. Use a newer version of this NuGet package or notify the library author."

The only package in my solution with a Xamarin.Android.Support.v4 dependency is Xam.Plugins.Notifier.

Plugin Version:  3.0.1
Platform:   Android 10, API 29
Device/Hardware:  N/A

### Expected behavior
Should be able to compile solution with Xam.Plugins.Notifier

### Actual behavior
Error above.

**Comment by jimiatnymbl** [comment]
Upgraded to Xamarin.Forms 4.8 (along with Visual Studio updates) and I am no longer receiving this error for Xam.Plugins.Notifier.  Oddly enough, I'm now receiving it for something else.  For anyone reading this, more information on this error can be found here:

https://docs.microsoft.com/en-us/xamarin/android/release-notes/10/10.2#xa0121-error-for-old-xamarinandroidsupport-library-versions

**Comment by JKennedy24** [comment]
To fix this error you need to install the Xamarin.Android.Support.V4 library manually and install V27.0.2 or higher.

looks like this github project is not supported.

Ideally it would upgrade to use the new AndroidX libraries, but for now manually installing the support package is a workaround
